import { defineField, defineType } from "sanity";
import { Mail } from "lucide-react";

const groupConfig = [
  { name: "subscribe", title: "Subscribe Form" },
  { name: "welcome", title: "Welcome Email" },
  { name: "unsubscribe", title: "Unsubscribe Page" },
  { name: "contact", title: "Contact Emails" },
  { name: "campaign", title: "Campaign Email" },
  { name: "dashboard", title: "Dashboard" },
  { name: "admin", title: "Admin Access" },
];

export const newsletterSettings = defineType({
  name: "newsletterSettings",
  title: "Newsletter Settings",
  type: "document",
  icon: Mail,
  groups: groupConfig,
  fields: [
    defineField({ name: "subscribeSuccess", title: "Subscribe Success", type: "localizedString", group: "subscribe" }),
    defineField({ name: "subscribeAlready", title: "Already Subscribed", type: "localizedString", group: "subscribe" }),
    defineField({ name: "subscribeError", title: "Subscribe Error", type: "localizedString", group: "subscribe" }),
    defineField({ name: "invalidEmail", title: "Invalid Email", type: "localizedString", group: "subscribe" }),
    defineField({ name: "tooManyRequests", title: "Too Many Requests", type: "localizedString", group: "subscribe" }),

    defineField({ name: "welcomeEmailSubject", title: "Welcome Email Subject", type: "localizedString", group: "welcome" }),
    defineField({ name: "welcomeEmailTitle", title: "Welcome Email Title", type: "localizedString", group: "welcome" }),
    defineField({ name: "welcomeEmailIntro", title: "Welcome Email Intro", type: "localizedText", group: "welcome" }),
    defineField({ name: "welcomeEmailBody", title: "Welcome Email Body", type: "localizedText", group: "welcome" }),

    defineField({ name: "newsletterPreferences", title: "Newsletter Preferences Label", type: "localizedString", group: "unsubscribe" }),
    defineField({ name: "unsubscribeLogo", title: "Unsubscribe Page Logo", type: "image", group: "unsubscribe", options: { hotspot: true } }),
    defineField({ name: "unsubscribeReactionImage", title: "Unsubscribe Reaction Image", type: "image", group: "unsubscribe", options: { hotspot: true } }),
    defineField({ name: "unsubscribeSuccessTitle", title: "Unsubscribe Success Title", type: "localizedString", group: "unsubscribe" }),
    defineField({ name: "unsubscribeSuccessMessage", title: "Unsubscribe Success Message", type: "localizedText", group: "unsubscribe" }),
    defineField({ name: "unsubscribeInvalidTitle", title: "Unsubscribe Invalid Title", type: "localizedString", group: "unsubscribe" }),
    defineField({ name: "unsubscribeInvalidMessage", title: "Unsubscribe Invalid Message", type: "localizedText", group: "unsubscribe" }),
    defineField({ name: "unsubscribeAlreadyTitle", title: "Unsubscribe Already/Not Found Title", type: "localizedString", group: "unsubscribe" }),
    defineField({ name: "unsubscribeAlreadyMessage", title: "Unsubscribe Already/Not Found Message", type: "localizedText", group: "unsubscribe" }),
    defineField({ name: "returnToWebsite", title: "Return To Website", type: "localizedString", group: "unsubscribe" }),

    defineField({ name: "contactSupportSubject", title: "Support Email Subject", type: "localizedString", group: "contact" }),
    defineField({ name: "contactSupportTitle", title: "Support Email Title", type: "localizedString", group: "contact" }),
    defineField({ name: "contactSupportIntro", title: "Support Email Intro", type: "localizedText", group: "contact" }),
    defineField({ name: "contactCustomerSubject", title: "Customer Email Subject", type: "localizedString", group: "contact" }),
    defineField({ name: "contactCustomerIntro", title: "Customer Email Intro", type: "localizedText", group: "contact" }),
    defineField({ name: "contactCustomerBody", title: "Customer Email Body", type: "localizedText", group: "contact" }),
    defineField({ name: "contactAckFooter", title: "Acknowledgement Footer", type: "localizedString", group: "contact" }),
    defineField({ name: "contactReplyFooter", title: "Support Reply Footer", type: "localizedString", group: "contact" }),

    defineField({ name: "contactLabel", title: "Contact Label", type: "localizedString", group: "campaign" }),
    defineField({ name: "bestRegards", title: "Best Regards", type: "localizedString", group: "campaign" }),
    defineField({ name: "unsubscribeLabel", title: "Unsubscribe Label", type: "localizedString", group: "campaign" }),
    defineField({ name: "campaignEyebrow", title: "Campaign Email Eyebrow", type: "localizedString", group: "campaign" }),
    defineField({ name: "subscribedReason", title: "Subscribed Reason Footer", type: "localizedText", group: "campaign" }),

    defineField({ name: "dashboardEyebrow", title: "Dashboard Eyebrow", type: "localizedString", group: "dashboard" }),
    defineField({ name: "dashboardTitle", title: "Dashboard Title", type: "localizedString", group: "dashboard" }),
    defineField({ name: "dashboardIntro", title: "Dashboard Intro", type: "localizedText", group: "dashboard" }),
    defineField({ name: "dashboardLibraryTitle", title: "Library Title", type: "localizedString", group: "dashboard" }),
    defineField({ name: "dashboardLibraryIntro", title: "Library Intro", type: "localizedString", group: "dashboard" }),
    defineField({ name: "dashboardEditorTitle", title: "Editor Title", type: "localizedString", group: "dashboard" }),
    defineField({ name: "dashboardCreatingDraft", title: "Creating Draft Text", type: "localizedString", group: "dashboard" }),
    defineField({ name: "dashboardEditingDraft", title: "Editing Draft Text", type: "localizedString", group: "dashboard" }),
    defineField({ name: "dashboardNewDraft", title: "New Draft Button", type: "localizedString", group: "dashboard" }),
    defineField({ name: "dashboardDraftsTab", title: "Drafts Tab", type: "localizedString", group: "dashboard" }),
    defineField({ name: "dashboardSentTab", title: "Sent Tab", type: "localizedString", group: "dashboard" }),

    defineField({ name: "adminTokenSubject", title: "Admin Access Token Subject", type: "localizedString", group: "admin" }),
    defineField({ name: "adminTokenTitle", title: "Admin Access Token Title", type: "localizedString", group: "admin" }),
    defineField({ name: "adminTokenBody", title: "Admin Access Token Body", type: "localizedText", group: "admin" }),
  ],
  initialValue: {
    subscribeSuccess: { ar: "تم الاشتراك بنجاح.", en: "Subscribed successfully." },
    subscribeAlready: { ar: "أنت مشترك بالفعل.", en: "You're already subscribed." },
    subscribeError: { ar: "تعذر الاشتراك الآن. يرجى المحاولة لاحقاً.", en: "Unable to subscribe right now. Please try again later." },
    invalidEmail: { ar: "يرجى إدخال بريد إلكتروني صحيح.", en: "Please enter a valid email address." },
    tooManyRequests: { ar: "طلبات كثيرة. يرجى المحاولة لاحقاً.", en: "Too many requests. Please try again later." },
    welcomeEmailSubject: { ar: "مرحباً بك في تحديثات فاشن غيت مول", en: "Welcome to Fashion Gate Mall updates" },
    welcomeEmailTitle: { ar: "مرحباً بك في تحديثات فاشن غيت مول", en: "Welcome to Fashion Gate Mall updates" },
    welcomeEmailIntro: {
      ar: "شكراً لاشتراكك في تحديثاتنا الخاصة. ستصلك دعوات مختارة، وإطلاقات المجموعات الموسمية، وأخبار فاشن غيت مول.",
      en: "Thank you for subscribing to our private updates. You will receive selected invitations, seasonal collection launches, and refined notes from Fashion Gate Mall.",
    },
    welcomeEmailBody: {
      ar: "تم اشتراكك بنجاح. سنبقيك قريباً من أحدث الدعوات والمجموعات الموسمية وتحديثات فاشن غيت مول الخاصة.",
      en: "You're subscribed. We'll keep you close to our latest invitations, seasonal collections, and private Fashion Gate Mall updates.",
    },
    contactLabel: { ar: "التواصل", en: "Contact" },
    bestRegards: { ar: "مع أطيب التحيات،", en: "Best regards," },
    unsubscribeLabel: { ar: "إلغاء الاشتراك", en: "Unsubscribe" },
    newsletterPreferences: { ar: "تفضيلات النشرة البريدية", en: "Newsletter Preferences" },
    unsubscribeSuccessTitle: { ar: "تم إلغاء اشتراكك", en: "You have been unsubscribed" },
    unsubscribeSuccessMessage: { ar: "لن تصلك تحديثات النشرة البريدية من فاشن غيت مول بعد الآن.", en: "You will no longer receive Fashion Gate Mall newsletter updates." },
    unsubscribeInvalidTitle: { ar: "تعذر تحديث اشتراكك", en: "Unable to update your subscription" },
    unsubscribeInvalidMessage: { ar: "رابط إلغاء الاشتراك غير صالح أو انتهت صلاحيته.", en: "This unsubscribe link is invalid or has expired." },
    unsubscribeAlreadyTitle: { ar: "تم تحديث الاشتراك مسبقاً", en: "Subscription already updated" },
    unsubscribeAlreadyMessage: { ar: "لم نتمكن من العثور على اشتراك نشط لهذا الرابط.", en: "We could not find an active subscription for this link." },
    returnToWebsite: { ar: "العودة إلى الموقع", en: "Return to website" },
    campaignEyebrow: { ar: "تحديثات خاصة", en: "Bespoke Updates" },
    subscribedReason: { ar: "تصلك هذه الرسالة لأنك اشتركت في تحديثات فاشن غيت مول.", en: "You are receiving this email because you subscribed on Fashion Gate Mall." },
    adminTokenSubject: { ar: "رمز الدخول إلى لوحة النشرة البريدية", en: "Fashion Gate Mall newsletter dashboard access token" },
    adminTokenTitle: { ar: "رمز الدخول الخاص بك", en: "Your Access Token" },
    adminTokenBody: { ar: "تنتهي صلاحية هذا الرمز خلال 10 دقائق. استخدمه فقط إذا طلبت الدخول إلى لوحة النشرة البريدية.", en: "This token expires in 10 minutes. Paste it in the newsletter dashboard only if you requested access." },
    contactSupportSubject: { ar: "استفسار جديد من الموقع", en: "New Website Enquiry - Fashion Gate Mall" },
    contactSupportTitle: { ar: "استفسار جديد من الموقع", en: "New website enquiry" },
    contactSupportIntro: { ar: "تم إرسال طلب تواصل جديد عبر موقع فاشن غيت مول.", en: "A new contact request has been submitted through the Fashion Gate Mall website." },
    contactCustomerSubject: { ar: "تم استلام رسالتك", en: "We received your message" },
    contactCustomerIntro: { ar: "وصلت رسالتك إلى فاشن غيت مول. سيقوم فريق خدمة العملاء بمراجعتها والرد عليك قريباً.", en: "Your message has reached Fashion Gate Mall. Our client services team will review it and get back to you shortly." },
    contactCustomerBody: { ar: "نقدّر تواصلك معنا. سيتابع أحد أعضاء فريقنا معك في أقرب وقت ممكن.", en: "We appreciate you taking the time to contact us. A member of our team will follow up with you as soon as possible." },
    contactAckFooter: { ar: "هذه رسالة تأكيد تلقائية من فاشن غيت مول.", en: "This is an automated acknowledgement from Fashion Gate Mall." },
    contactReplyFooter: { ar: "يمكنك الرد على هذه الرسالة للتواصل مباشرة مع العميل.", en: "Reply to this email to respond directly to the customer." },
    dashboardEyebrow: { ar: "فاشن غيت مول", en: "Fashion Gate Mall" },
    dashboardTitle: { ar: "لوحة النشرة البريدية", en: "Newsletter Dashboard" },
    dashboardIntro: { ar: "أنشئ تحديثات أنيقة، أرسل بريداً تجريبياً للمراجعة، ثم أرسل الحملة للمشتركين فقط.", en: "Create polished updates, send a test email for approval, then send the campaign to subscribed users only." },
    dashboardLibraryTitle: { ar: "مكتبة الحملات", en: "Campaign Library" },
    dashboardLibraryIntro: { ar: "اختر مسودة محفوظة أو حملة مرسلة.", en: "Select a saved draft or sent campaign." },
    dashboardEditorTitle: { ar: "محرر الحملة", en: "Campaign Editor" },
    dashboardCreatingDraft: { ar: "إنشاء مسودة جديدة", en: "Creating new draft" },
    dashboardEditingDraft: { ar: "تعديل مسودة محفوظة", en: "Editing saved draft" },
    dashboardNewDraft: { ar: "مسودة جديدة", en: "New Draft" },
    dashboardDraftsTab: { ar: "المسودات", en: "Drafts" },
    dashboardSentTab: { ar: "المرسلة", en: "Sent" },
  },
  preview: {
    prepare() {
      return { title: "Newsletter Settings" };
    },
  },
});
